language: node_js
node_js:
  - "10"
env:
  - CI=true
cache: yarn
git:
  depth: 5
script:
  - yarn build
  - yarn test:cover
  - if [ "${CIRCLE_BRANCH}" != "master" ];
    then
    yarn chromatic
    else
    yarn chromatic --auto-accept-changes
    fi
